### ISSUE TITLE
GlobalStreamId __hash__

### ISSUE THREAD

**Issue by as595** [AirSage/Petrel#66]
I'm getting an error running petrel for the wordcount example:

asdisplay:wordcount AMMS$ sudo ./buildandrun --config topology.yaml 
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/AMMS/SRC/PETREL/Petrel/petrel/petrel/cmdline.py", line 12, in <module>
    from .package import build_jar
  File "/Users/AMMS/SRC/PETREL/Petrel/petrel/petrel/package.py", line 13, in <module>
    from topologybuilder import TopologyBuilder
  File "/Users/AMMS/SRC/PETREL/Petrel/petrel/petrel/topologybuilder.py", line 15, in <module>
    assert not hasattr(GlobalStreamId, '__hash__')
AssertionError
Error on or near line 24; exiting with status 1

I think this is because the GlobalStreamId does have a __hash__ function already. So the "assert not" line (topologybuilder.py, line 15) should either be changed to "assert" or commented out?

**Comment by barrywhart** [comment]
I cannot reproduce this issue. Please provide instructions on how to do so. I suspect you are running with a different version of Storm, Python Thrift, or some other dependency.

Tested with Storm 0.9.4 and Python Thrift 0.8.0.
