### ISSUE TITLE
Unable to run petrel example

### ISSUE THREAD

**Issue by pavn** [AirSage/Petrel#69]
Hi I get this error while running the petrel sample. Followed your instructions. Please can you help:

I am using apache Storm 0.9.3, Petrel 0.9.3.0.3

Error log:
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/newuser/apache-storm/bin/petrel/lib/python2.7/site-packages/petrel-0.9.3.0.3-py2.7.egg/petrel/cmdline.py", line 111, in main
    func(**args.__dict__)
  File "/home/newuser/apache-storm/bin/petrel/lib/python2.7/site-packages/petrel-0.9.3.0.3-py2.7.egg/petrel/cmdline.py", line 32, in submit
    sourcejar = get_sourcejar()
  File "/home/newuser/apache-storm/bin/petrel/lib/python2.7/site-packages/petrel-0.9.3.0.3-py2.7.egg/petrel/cmdline.py", line 23, in get_sourcejar
    storm_version = get_storm_version()
  File "/home/newuser/apache-storm/bin/petrel/lib/python2.7/site-packages/petrel-0.9.3.0.3-py2.7.egg/petrel/cmdline.py", line 17, in get_storm_version
    version = subprocess.check_output(['storm', 'version']).strip()
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by barrywhart** [comment]
Looks like the storm executable is not in your PATH.
