### ISSUE TITLE
Python 3.5 strange error

### ISSUE THREAD

**Issue by dmitry-saritasa** [AirSage/Petrel#84]
```
petrel submit --config topology.yaml --logdir `pwd`
```

I get the following error

```shell
(storm) ➜  src git:(develop) ✗ petrel submit --config topology.yaml --logdir `pwd`
Adding resources/__submitter__.yaml
Adding resources/__topology__.yaml
[2017-03-25 18:17:55,220][kafka.client][INFO]Bootstrapping cluster metadata from [('localhost', 9092, <AddressFamily.AF_UNSPEC: 0>)]
[2017-03-25 18:17:55,224][kafka.conn][INFO]<BrokerConnection node_id=bootstrap host=localhost/::1 port=9092>: connecting to ::1:9092
[2017-03-25 18:17:55,228][kafka.client][INFO]Bootstrap succeeded: found 1 brokers and 4 topics.
[2017-03-25 18:17:55,228][kafka.conn][INFO]<BrokerConnection node_id=bootstrap host=localhost/::1 port=9092>: Closing connection. 
[2017-03-25 18:17:55,290][kafka.conn][INFO]<BrokerConnection node_id=0 host=ip-192-168-15-75.us-west-2.compute.internal/192.168.15.75 port=9092>: connecting to 192.168.15.75:9092
[2017-03-25 18:17:55,395][kafka.conn][INFO]Broker version identifed as 0.10.0
[2017-03-25 18:17:55,395][kafka.conn][INFO]Set configuration api_version=(0, 10, 0) to skip auto check_version requests on startup
[2017-03-25 18:17:55,398][kafka.consumer.subscription_state][INFO]Updating subscribed topics to: ('viewability', 'engagement')
/home/dmitry/Projects/trivver/storm/src/topology/spouts/kafka_stream.py

Traceback (most recent call last):
  File "/home/dmitry/Projects/trivver/storm/src/.venv/storm/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg/petrel/cmdline.py", line 126, in main
    func(**args.__dict__)
  File "/home/dmitry/Projects/trivver/storm/src/.venv/storm/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg/petrel/cmdline.py", line 54, in submit
    logdir=logdir)
  File "/home/dmitry/Projects/trivver/storm/src/.venv/storm/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg/petrel/package.py", line 132, in build_jar
    getattr(module, function_name)(builder)
  File "/home/dmitry/Projects/trivver/storm/src/create.py", line 6, in create
    builder.setSpout("spout", KafkaSpout(), 1)
  File "/home/dmitry/Projects/trivver/storm/src/topology/spouts/kafka_stream.py", line 18, in __init__
    super().__init__(script=__file__)
  File "/home/dmitry/Projects/trivver/storm/src/.venv/storm/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg/petrel/emitter.py", line 18, in __init__
    assert len(path) == 0
AssertionError

```

```python
import config as cfg
from petrel import storm
from petrel.emitter import Spout

# enable loggers
log = cfg.config.loggers.kafka


class KafkaSpout(Spout):

    def __init__(self):
        self.stream = cfg.config.kafka
        print(__file__) # prints /home/dmitry/Projects/trivver/storm/src/topology/spouts/kafka_stream.py
        super().__init__(script=__file__) # this is line 18

    @classmethod
    def declareOutputFields(cls):
        return ['record', 'topic']

    def nextTuple(self):
        record = next(self.stream)
        log.info("{}:{}:{}: key={} value={}".format(
            record.topic,
            record.partition,
            record.offset,
            record.key,
            record.value))

        storm.emit([record, record.topic])


def run():
    KafkaSpout().run()

```

**Comment by barrywhart** [comment]
Based on the comments in the code, Petrel is assuming the spout or bolt script is in the current directory. I'm guessing your script is somewhere else (e.g. a subdirectory).

See the comments just above the assertion failure:
https://github.com/AirSage/Petrel/blob/master/petrel/petrel/emitter.py#L14-L18

**Comment by dmitry-saritasa** [comment]
Thanks Barry for the quick answer 
so i can't have bolts/spouts in subdirectory? they should be at the same level as create.py?

**Comment by barrywhart** [comment]
That's right. I haven't looked closely at the code, but this requirement could probably be removed.

**Comment by dmitry-saritasa** [comment]
I see - thanks. It works, another question I have is how do I push virtualenvironment inside jar file
ls -la .venv/storm/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg

I'm getting the following error:

```
Beginning task setup
/usr/bin/flock
Using existing venv: /tmp/petrel-20topology-1-1490493473/venv
Task setup took 8 seconds
Launching: python -m petrel.run kafka_stream /home/dmitry/code/trivver/storm/src/petrel26633_kafka_stream.log
/tmp/petrel-20topology-1-1490493473/venv/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg/petrel/run.py invoked with the following arguments: ['kafka_stream', '/home/dmitry/code/trivver/storm/src/petrel26633_kafka_stream.log']
python version: 3.5.2
user=dmitry
PATH=/tmp/petrel-20topology-1-1490493473/venv/bin:/home/dmitry/Projects/trivver/storm/src/.venv/storm/bin:/home/dmitry/Development/google-cloud-sdk/bin:/home/dmitry/.pyenv/plugins/pyenv-virtualenv/shims:/home/dmitry/.pyenv/shims:/home/dmitry/.pyenv/bin:/home/dmitry/.pyenv/plugins/pyenv-virtualenv/shims:/home/dmitry/.pyenv/shims:/home/dmitry/.pyenv/bin:/home/dmitry/perl5/bin:/home/dmitry/Development/google-cloud-sdk/bin:/home/dmitry/.pyenv/plugins/pyenv-virtualenv/shims:/home/dmitry/.pyenv/shims:/home/dmitry/.pyenv/bin:/home/dmitry/.pyenv/plugins/pyenv-virtualenv/shims:/home/dmitry/.pyenv/shims:/home/dmitry/.pyenv/bin:/home/dmitry/perl5/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/dmitry/bin:/usr/local/bin:/home/dmitry/Music/convert:/bin:/home/dmitry/.go/bin:/home/dmitry/Development/storm/bin:/home/dmitry/Development/kafka/bin:/home/dmitry/Development:/home/dmitry/Development/hbase/bin:/home/dmitry/Development/IDE/lightable:/home/dmitry/Development/zookeeper:/home/dmitry/Development/zookeeper/bin:/home/dmitry/Android/Sdk:/home/dmitry/Android/Sdk/tools::/home/dmitry/Android/Sdk/platform-tools:/home/dmitry/.fzf/bin:/home/dmitry/bin:/usr/local/bin:/home/dmitry/Music/convert:/bin:/home/dmitry/.go/bin:/home/dmitry/Development/storm/bin:/home/dmitry/Development/kafka/bin:/home/dmitry/Development:/home/dmitry/Development/hbase/bin:/home/dmitry/Development/IDE/lightable:/home/dmitry/Development/zookeeper:/home/dmitry/Development/zookeeper/bin:/home/dmitry/Android/Sdk:/home/dmitry/Android/Sdk/tools::/home/dmitry/Android/Sdk/platform-tools
LD_LIBRARY_PATH=None
PYTHON_EGG_CACHE=/tmp/petrel-20topology-1-1490493473/egg_cache
[2017-03-25 18:58:06,780][storm][INFO]Tuple profiling enabled. Will log tuple processing times.
[2017-03-25 18:58:06,783][petrel.run][ERROR]E_RUNFAILED_kafka_stream_dmitry.npb.saritasa.io_26633_ImportError
[2017-03-25 18:58:06,784][storm][ERROR]Sent failure message ("E_RUNFAILED_kafka_stream_dmitry.npb.saritasa.io_26633_ImportError") to Storm
Exception occurred in kafka_stream. Worker exiting.
Traceback (most recent call last):
  File "/tmp/petrel-20topology-1-1490493473/venv/lib/python3.5/site-packages/petrel-1.0.2.0.3-py3.5.egg/petrel/run.py", line 105, in main
    module = __import__(module_name)
  File "/tmp/a4a1fe01-db6d-4b41-ad3f-8fc149ae6716/supervisor/stormdist/test%20topology-1-1490493473/resources/kafka_stream.py", line 5, in <module>
    import config as cfg
  File "/tmp/a4a1fe01-db6d-4b41-ad3f-8fc149ae6716/supervisor/stormdist/test%20topology-1-1490493473/resources/config/__init__.py", line 3, in <module>
    from .config import load
  File "/tmp/a4a1fe01-db6d-4b41-ad3f-8fc149ae6716/supervisor/stormdist/test%20topology-1-1490493473/resources/config/config.py", line 8, in <module>
    import slacker
ImportError: No module named 'slacker'
```

and the slacker module is part of my virtual environment

**Comment by barrywhart** [comment]
Please read this part of the README: https://github.com/AirSage/Petrel#deploy-and-run.

Briefly, the `--venv` parameter is only intended for local testing, not for deploying/running on a cluster. On a cluster, Petrel creates a *new* virtualenv each time you deploy, and you are responsible for installing the Python packages into that new virtualenv by adding commands to your `setup.sh`.
